import { miroClient } from './miroClient';
import { 
  Project, 
  PitchAnalysis, 
  PitchDeck, 
  PitchAttackReport, 
  JudgeQuestion, 
  ExecutiveSummary 
} from '@/types';

export interface WritePitchOptions {
  boardId: string;
  project: Project;
  analysis: PitchAnalysis;
  deck: PitchDeck;
  attackReport: PitchAttackReport;
  judgeQuestions: JudgeQuestion[];
  summary: ExecutiveSummary;
  replaceExisting?: boolean;
  createVersion?: boolean;
}

export interface WritePitchResult {
  success: boolean;
  boardId: string;
  boardUrl: string;
  frameId: string;
  frameTitle: string;
  itemsCreatedCount: number;
  message: string;
  needsConfirmation?: boolean;
  existingFrameTitle?: string;
  nextVersion?: number;
}

const DELAY_BETWEEN_CALLS_MS = 80;

function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

export async function writePitchToMiro(options: WritePitchOptions): Promise<WritePitchResult> {
  const { 
    boardId, 
    project, 
    analysis, 
    deck, 
    attackReport, 
    judgeQuestions, 
    summary,
    replaceExisting = false,
    createVersion = false 
  } = options;

  if (!miroClient.isConfigured()) {
    throw new Error('MIRO_AUTHENTICATION_REQUIRED: Please authenticate your Miro account via OAuth before sending pitch to Miro.');
  }

  // 1. Check for existing frames
  const existingFrames = await miroClient.getFrames(boardId);
  const pitchForgeFrames = existingFrames.filter((f: any) => 
    f.data?.title && f.data.title.includes('PitchForge AI Pitch')
  );

  let version = 1;
  let targetFrameTitle = '🚀 PitchForge AI Pitch';

  if (pitchForgeFrames.length > 0) {
    // Determine the highest version found
    for (const f of pitchForgeFrames) {
      const match = f.data.title.match(/v(\d+)/i);
      if (match) {
        const v = parseInt(match[1], 10);
        if (v >= version) version = v + 1;
      } else {
        if (version === 1) version = 2;
      }
    }

    if (!replaceExisting && !createVersion) {
      return {
        success: false,
        needsConfirmation: true,
        boardId,
        boardUrl: `https://miro.com/app/board/${boardId}`,
        frameId: pitchForgeFrames[0].id,
        frameTitle: pitchForgeFrames[0].data.title,
        nextVersion: version,
        itemsCreatedCount: 0,
        message: 'PitchForge already has a generated pitch on this board. Replace it or create a new version?',
      };
    }

    if (createVersion) {
      targetFrameTitle = `🚀 PitchForge AI Pitch — v${version}`;
    }
  }

  // Calculate frame position (if creating new version, shift X coordinates so frames don't collide)
  let frameX = 0;
  let frameY = 0;

  if (createVersion && pitchForgeFrames.length > 0) {
    // Find the rightmost frame
    const rightmost = pitchForgeFrames.reduce((max: number, f: any) => {
      return Math.max(max, f.position?.x || 0);
    }, 0);
    frameX = rightmost + 4200;
  }

  const frameWidth = 3800;
  const frameHeight = 3600;

  // 2. If replaceExisting, delete old frame if we want a fresh replace
  if (replaceExisting && pitchForgeFrames.length > 0) {
    try {
      await miroClient.deleteItem(boardId, pitchForgeFrames[0].id);
      await sleep(200);
    } catch (delErr) {
      console.warn('Could not delete old frame:', delErr);
    }
  }

  // 3. Create parent Frame
  const frame = await miroClient.createFrame(boardId, {
    title: targetFrameTitle,
    x: frameX,
    y: frameY,
    width: frameWidth,
    height: frameHeight,
  });

  const frameId = frame.id;
  let itemsCount = 1; // frame counted

  // Helper to place item relative to frame center
  const place = (relX: number, relY: number) => ({
    x: frameX + relX,
    y: frameY + relY,
  });

  // 4. Header Titles inside frame
  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createText(boardId, {
    content: `<h1>🚀 PitchForge AI Pitch: ${project.name}</h1>`,
    ...place(0, -1650),
    width: 2200,
    parentId: frameId,
  });
  itemsCount++;

  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createText(boardId, {
    content: `<p>🤖 Generated by PitchForge • Miro + Qwen Reasoning Studio • Target Wedge: <strong>${project.targetAudience}</strong></p>`,
    ...place(0, -1580),
    width: 2000,
    parentId: frameId,
  });
  itemsCount++;

  // 5. Row 1: Problem & Target Users
  // Heading: Problem
  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createText(boardId, {
    content: `<h3>🔴 Problem Statement</h3><p><em>🤖 Generated by PitchForge</em></p>`,
    ...place(-1250, -1450),
    width: 600,
    parentId: frameId,
  });
  itemsCount++;

  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createStickyNote(boardId, {
    content: `${project.problemStatement}\n\n[Verified Problem Space]`,
    ...place(-1250, -1300),
    color: 'red',
    parentId: frameId,
  });
  itemsCount++;

  // Heading: Target Users
  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createText(boardId, {
    content: `<h3>👥 Target Customer Persona</h3><p><em>🤖 Generated by PitchForge</em></p>`,
    ...place(-450, -1450),
    width: 600,
    parentId: frameId,
  });
  itemsCount++;

  for (let i = 0; i < Math.min(2, analysis.targetUsers.length); i++) {
    await sleep(DELAY_BETWEEN_CALLS_MS);
    await miroClient.createStickyNote(boardId, {
      content: `${analysis.targetUsers[i]}\n\n[Target Wedge]`,
      ...place(-450, -1300 + i * 220),
      color: 'light_blue',
      parentId: frameId,
    });
    itemsCount++;
  }

  // 6. Architecture Nodes & Connectors (Top Right quadrant)
  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createText(boardId, {
    content: `<h3>🏗️ Technical Architecture & Pipeline</h3><p><em>🤖 Generated by PitchForge</em></p>`,
    ...place(800, -1450),
    width: 1000,
    parentId: frameId,
  });
  itemsCount++;

  // Architecture Box 1: Ingestion
  await sleep(DELAY_BETWEEN_CALLS_MS);
  const arch1 = await miroClient.createShape(boardId, {
    content: `<strong>Miro Workspace Canvas</strong><br>Sticky Notes • AST Trees`,
    ...place(400, -1300),
    width: 260,
    height: 90,
    shape: 'round_rectangle',
    fillColor: '#0F172A',
    textColor: '#94A3B8',
    borderColor: '#38BDF8',
    parentId: frameId,
  });
  itemsCount++;

  // Architecture Box 2: Reasoning Engine
  await sleep(DELAY_BETWEEN_CALLS_MS);
  const arch2 = await miroClient.createShape(boardId, {
    content: `<strong>Qwen Reasoning Core</strong><br>Multi-Turn Deductive Engine`,
    ...place(750, -1300),
    width: 260,
    height: 90,
    shape: 'round_rectangle',
    fillColor: '#1E1B4B',
    textColor: '#C7D2FE',
    borderColor: '#6366F1',
    parentId: frameId,
  });
  itemsCount++;

  // Architecture Box 3: Verification Gate
  await sleep(DELAY_BETWEEN_CALLS_MS);
  const arch3 = await miroClient.createShape(boardId, {
    content: `<strong>Evidence & Safety Gate</strong><br>85% Confidence Threshold`,
    ...place(1100, -1300),
    width: 260,
    height: 90,
    shape: 'round_rectangle',
    fillColor: '#064E3B',
    textColor: '#A7F3D0',
    borderColor: '#10B981',
    parentId: frameId,
  });
  itemsCount++;

  // Architecture Box 4: Deliverables
  await sleep(DELAY_BETWEEN_CALLS_MS);
  const arch4 = await miroClient.createShape(boardId, {
    content: `<strong>Pitch Studio Assets</strong><br>PPTX • Script • Judge Defense`,
    ...place(750, -1120),
    width: 280,
    height: 90,
    shape: 'round_rectangle',
    fillColor: '#1E293B',
    textColor: '#F8FAFC',
    borderColor: '#F59E0B',
    parentId: frameId,
  });
  itemsCount++;

  // Connectors
  try {
    await sleep(DELAY_BETWEEN_CALLS_MS);
    await miroClient.createConnector(boardId, {
      startItemId: arch1.id,
      endItemId: arch2.id,
      caption: 'Normalized Canvas',
      strokeColor: '#38BDF8',
    });
    itemsCount++;

    await sleep(DELAY_BETWEEN_CALLS_MS);
    await miroClient.createConnector(boardId, {
      startItemId: arch2.id,
      endItemId: arch3.id,
      caption: 'Inference',
      strokeColor: '#6366F1',
    });
    itemsCount++;

    await sleep(DELAY_BETWEEN_CALLS_MS);
    await miroClient.createConnector(boardId, {
      startItemId: arch3.id,
      endItemId: arch4.id,
      caption: 'Verified',
      strokeColor: '#10B981',
    });
    itemsCount++;
  } catch (connErr) {
    console.warn('Connector creation warning:', connErr);
  }

  // 7. Row 2: Chronic Pain Points & Proposed Solution
  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createText(boardId, {
    content: `<h3>⚡ Chronic Pain Points</h3><p><em>🤖 Generated by PitchForge</em></p>`,
    ...place(-1250, -980),
    width: 600,
    parentId: frameId,
  });
  itemsCount++;

  for (let i = 0; i < Math.min(2, analysis.painPoints.length); i++) {
    await sleep(DELAY_BETWEEN_CALLS_MS);
    await miroClient.createStickyNote(boardId, {
      content: `${analysis.painPoints[i]}`,
      ...place(-1250, -840 + i * 210),
      color: 'orange',
      parentId: frameId,
    });
    itemsCount++;
  }

  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createText(boardId, {
    content: `<h3>💡 Proposed Solution</h3><p><em>🤖 Generated by PitchForge</em></p>`,
    ...place(-450, -980),
    width: 600,
    parentId: frameId,
  });
  itemsCount++;

  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createStickyNote(boardId, {
    content: `${project.solutionDescription || analysis.proposedSolution}\n\n[Core Proposition]`,
    ...place(-450, -840),
    color: 'light_green',
    parentId: frameId,
  });
  itemsCount++;

  // Value Proposition Shape
  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createShape(boardId, {
    content: `<strong>VALUE PROPOSITION</strong><br>${analysis.valueProposition}`,
    ...place(-450, -600),
    width: 500,
    height: 120,
    shape: 'round_rectangle',
    fillColor: '#1E1B4B',
    textColor: '#E0E7FF',
    borderColor: '#818CF8',
    parentId: frameId,
  });
  itemsCount++;

  // 8. Pitch Readiness Score Section (Prominent Score Banner)
  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createText(boardId, {
    content: `<h3>📊 PITCH READINESS SCORE</h3><p><em>🤖 Generated by PitchForge • Calibrated Metric</em></p>`,
    ...place(800, -980),
    width: 900,
    parentId: frameId,
  });
  itemsCount++;

  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createShape(boardId, {
    content: `<strong>PITCH READINESS</strong><br><span style="font-size: 32px; font-weight: bold;">${analysis.pitchReadinessScore} / 100</span><br>Battle-Tested Scrutiny Rating`,
    ...place(800, -840),
    width: 450,
    height: 130,
    shape: 'round_rectangle',
    fillColor: '#064E3B',
    textColor: '#FFFFFF',
    borderColor: '#34D399',
    parentId: frameId,
  });
  itemsCount++;

  // Score breakdown stickies
  const breakdownStickyText = [
    `Problem Clarity: ${analysis.readinessBreakdown.problemClarity.score}/100`,
    `Solution Clarity: ${analysis.readinessBreakdown.solutionClarity.score}/100`,
    `Target User: ${analysis.readinessBreakdown.targetUserClarity.score}/100`,
    `Differentiation: ${analysis.readinessBreakdown.differentiation.score}/100`,
    `Empirical Evidence: ${analysis.readinessBreakdown.evidence.score}/100`,
    `Technical Feasibility: ${analysis.readinessBreakdown.technicalFeasibility.score}/100`,
  ].join('\n');

  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createStickyNote(boardId, {
    content: `SCORE BREAKDOWN:\n\n${breakdownStickyText}`,
    ...place(800, -640),
    color: 'yellow',
    parentId: frameId,
  });
  itemsCount++;

  // 9. Row 3: Competitive Differentiation & Business Model
  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createText(boardId, {
    content: `<h3>⚔️ Competitive Differentiation</h3><p><em>🤖 Generated by PitchForge</em></p>`,
    ...place(-1250, -380),
    width: 600,
    parentId: frameId,
  });
  itemsCount++;

  for (let i = 0; i < Math.min(2, analysis.differentiators.length); i++) {
    await sleep(DELAY_BETWEEN_CALLS_MS);
    await miroClient.createStickyNote(boardId, {
      content: `${analysis.differentiators[i]}\n\n[Defensible Moat]`,
      ...place(-1250, -240 + i * 200),
      color: 'violet',
      parentId: frameId,
    });
    itemsCount++;
  }

  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createText(boardId, {
    content: `<h3>💼 Business Model & Monetization</h3><p><em>🤖 Generated by PitchForge</em></p>`,
    ...place(-450, -380),
    width: 600,
    parentId: frameId,
  });
  itemsCount++;

  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createStickyNote(boardId, {
    content: `${analysis.businessModel || 'Freemium SaaS with usage-based enterprise tier.'}\n\n[Monetization Model]`,
    ...place(-450, -240),
    color: 'yellow',
    parentId: frameId,
  });
  itemsCount++;

  // 10. Critical Issues / 🔥 ATTACK MY PITCH
  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createText(boardId, {
    content: `<h2>🔥 ATTACK MY PITCH (Skeptical Counter-Critique)</h2><p><em>🤖 Generated by PitchForge • Survival Score: ${attackReport.survivalScore}/100</em></p>`,
    ...place(0, 100),
    width: 2500,
    parentId: frameId,
  });
  itemsCount++;

  const topAttacks = attackReport.attacks.slice(0, 3);
  const attackCols = [-1000, 0, 1000];
  for (let i = 0; i < topAttacks.length; i++) {
    const atk = topAttacks[i];
    await sleep(DELAY_BETWEEN_CALLS_MS);
    await miroClient.createStickyNote(boardId, {
      content: `🔴 ${atk.severity.toUpperCase()}: ${atk.category}\n\nIssue: ${atk.issue}\n\nWhy It Matters: ${atk.whyItMatters}\n\nFix: ${atk.recommendedFix}`,
      ...place(attackCols[i], 270),
      color: atk.severity === 'critical' ? 'red' : 'orange',
      parentId: frameId,
    });
    itemsCount++;
  }

  // 11. Recommended Improvements (3 things before presenting)
  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createText(boardId, {
    content: `<h3>🛠️ 3 Recommended Improvements Before Presenting</h3><p><em>🤖 Generated by PitchForge</em></p>`,
    ...place(0, 520),
    width: 2500,
    parentId: frameId,
  });
  itemsCount++;

  const recChanges = analysis.recommendedChanges.slice(0, 3);
  for (let i = 0; i < recChanges.length; i++) {
    await sleep(DELAY_BETWEEN_CALLS_MS);
    await miroClient.createStickyNote(boardId, {
      content: `Recommendation 0${i + 1}:\n\n${recChanges[i]}\n\n[Action Item]`,
      ...place(attackCols[i], 660),
      color: 'light_green',
      parentId: frameId,
    });
    itemsCount++;
  }

  // 12. Pitch Script Section
  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createText(boardId, {
    content: `<h2>🎤 10-Slide Pitch Narrative & Speaker Script</h2><p><em>🤖 Generated by PitchForge • Total Speaking Time: ~${Math.ceil(deck.totalDurationSeconds / 60)} mins</em></p>`,
    ...place(0, 950),
    width: 2500,
    parentId: frameId,
  });
  itemsCount++;

  // Create 5 columns of slides x 2 rows
  const slideColWidth = 550;
  for (let i = 0; i < Math.min(10, deck.slides.length); i++) {
    const s = deck.slides[i];
    const row = i < 5 ? 0 : 1;
    const col = i % 5;
    const posX = -1100 + col * slideColWidth;
    const posY = 1120 + row * 280;

    await sleep(DELAY_BETWEEN_CALLS_MS);
    await miroClient.createStickyNote(boardId, {
      content: `Slide ${s.slideNumber}: ${s.title} (${s.durationSeconds}s)\n\nScript: "${s.speakerScript.slice(0, 160)}..."\n\nDelivery: ${s.deliveryNotes?.tone || 'Confident'}`,
      ...place(posX, posY),
      color: row === 0 ? 'yellow' : 'cyan',
      parentId: frameId,
    });
    itemsCount++;
  }

  // 13. Judge Questions Section
  await sleep(DELAY_BETWEEN_CALLS_MS);
  await miroClient.createText(boardId, {
    content: `<h2>🎯 AI JUDGE QUESTIONS (Grounded Defense Prep)</h2><p><em>🤖 Generated by PitchForge • Tough Cross-Examination</em></p>`,
    ...place(0, 1800),
    width: 2500,
    parentId: frameId,
  });
  itemsCount++;

  const topQuestions = judgeQuestions.slice(0, 6);
  for (let i = 0; i < topQuestions.length; i++) {
    const q = topQuestions[i];
    const row = i < 3 ? 0 : 1;
    const col = i % 3;
    const posX = -900 + col * 900;
    const posY = 1960 + row * 280;

    await sleep(DELAY_BETWEEN_CALLS_MS);
    await miroClient.createStickyNote(boardId, {
      content: `[${q.category.toUpperCase()} • ${q.difficulty} Difficulty]\n\nQ: "${q.question}"\n\nAnswer: ${q.suggestedAnswer.slice(0, 180)}...\n\n${q.evidenceNeeded ? `Evidence Needed: ${q.evidenceNeeded}` : '[Context Grounded]'}`,
      ...place(posX, posY),
      color: q.evidenceStatus === 'evidence-needed' ? 'pink' : 'light_blue',
      parentId: frameId,
    });
    itemsCount++;
  }

  return {
    success: true,
    boardId,
    boardUrl: `https://miro.com/app/board/${boardId}`,
    frameId,
    frameTitle: targetFrameTitle,
    itemsCreatedCount: itemsCount,
    message: `Successfully created structured pitch workspace "${targetFrameTitle}" with ${itemsCount} items on Miro board.`,
  };
}
